package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airline generated by hbm2java
 */
public class Airline  implements java.io.Serializable {


     private int airlineId;
     private String airlineName;
     private String airlineAddress;
     private String airlineCountry;
     private String airlineSite;
     private String airlineEmail;
     private Set<Rent> rents = new HashSet<Rent>(0);
     private Set<Airplane> airplanes = new HashSet<Airplane>(0);
     private Set<User> users = new HashSet<User>(0);

    public Airline() {
    }

	
    public Airline(int airlineId, String airlineName, String airlineAddress, String airlineCountry, String airlineSite, String airlineEmail) {
        this.airlineId = airlineId;
        this.airlineName = airlineName;
        this.airlineAddress = airlineAddress;
        this.airlineCountry = airlineCountry;
        this.airlineSite = airlineSite;
        this.airlineEmail = airlineEmail;
    }
    public Airline(int airlineId, String airlineName, String airlineAddress, String airlineCountry, String airlineSite, String airlineEmail, Set<Rent> rents, Set<Airplane> airplanes, Set<User> users) {
       this.airlineId = airlineId;
       this.airlineName = airlineName;
       this.airlineAddress = airlineAddress;
       this.airlineCountry = airlineCountry;
       this.airlineSite = airlineSite;
       this.airlineEmail = airlineEmail;
       this.rents = rents;
       this.airplanes = airplanes;
       this.users = users;
    }
   
    public int getAirlineId() {
        return this.airlineId;
    }
    
    public void setAirlineId(int airlineId) {
        this.airlineId = airlineId;
    }
    public String getAirlineName() {
        return this.airlineName;
    }
    
    public void setAirlineName(String airlineName) {
        this.airlineName = airlineName;
    }
    public String getAirlineAddress() {
        return this.airlineAddress;
    }
    
    public void setAirlineAddress(String airlineAddress) {
        this.airlineAddress = airlineAddress;
    }
    public String getAirlineCountry() {
        return this.airlineCountry;
    }
    
    public void setAirlineCountry(String airlineCountry) {
        this.airlineCountry = airlineCountry;
    }
    public String getAirlineSite() {
        return this.airlineSite;
    }
    
    public void setAirlineSite(String airlineSite) {
        this.airlineSite = airlineSite;
    }
    public String getAirlineEmail() {
        return this.airlineEmail;
    }
    
    public void setAirlineEmail(String airlineEmail) {
        this.airlineEmail = airlineEmail;
    }
    public Set<Rent> getRents() {
        return this.rents;
    }
    
    public void setRents(Set<Rent> rents) {
        this.rents = rents;
    }
    public Set<Airplane> getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Set<Airplane> airplanes) {
        this.airplanes = airplanes;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


