package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airplane generated by hbm2java
 */
public class Airplane  implements java.io.Serializable {


     private int airplaneId;
     private Airline airline;
     private Airplanetype airplanetype;
     private Manufacturer manufacturer;
     private String airplaneName;
     private Set<Rent> rents = new HashSet<Rent>(0);
     private Set<Flight> flights = new HashSet<Flight>(0);

    public Airplane() {
    }

	
    public Airplane(int airplaneId, Airline airline, Airplanetype airplanetype, Manufacturer manufacturer, String airplaneName) {
        this.airplaneId = airplaneId;
        this.airline = airline;
        this.airplanetype = airplanetype;
        this.manufacturer = manufacturer;
        this.airplaneName = airplaneName;
    }
    public Airplane(int airplaneId, Airline airline, Airplanetype airplanetype, Manufacturer manufacturer, String airplaneName, Set<Rent> rents, Set<Flight> flights) {
       this.airplaneId = airplaneId;
       this.airline = airline;
       this.airplanetype = airplanetype;
       this.manufacturer = manufacturer;
       this.airplaneName = airplaneName;
       this.rents = rents;
       this.flights = flights;
    }
   
    public int getAirplaneId() {
        return this.airplaneId;
    }
    
    public void setAirplaneId(int airplaneId) {
        this.airplaneId = airplaneId;
    }
    public Airline getAirline() {
        return this.airline;
    }
    
    public void setAirline(Airline airline) {
        this.airline = airline;
    }
    public Airplanetype getAirplanetype() {
        return this.airplanetype;
    }
    
    public void setAirplanetype(Airplanetype airplanetype) {
        this.airplanetype = airplanetype;
    }
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getAirplaneName() {
        return this.airplaneName;
    }
    
    public void setAirplaneName(String airplaneName) {
        this.airplaneName = airplaneName;
    }
    public Set<Rent> getRents() {
        return this.rents;
    }
    
    public void setRents(Set<Rent> rents) {
        this.rents = rents;
    }
    public Set<Flight> getFlights() {
        return this.flights;
    }
    
    public void setFlights(Set<Flight> flights) {
        this.flights = flights;
    }




}


