package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airplanetype generated by hbm2java
 */
public class Airplanetype  implements java.io.Serializable {


     private int airplaneTypeId;
     private Manufacturer manufacturer;
     private String airplaneTypeName;
     private String airplaneTypeLicence;
     private int airplaneTypeSeatsNumber;
     private Set<Airplane> airplanes = new HashSet<Airplane>(0);

    public Airplanetype() {
    }

	
    public Airplanetype(int airplaneTypeId, Manufacturer manufacturer, String airplaneTypeName, String airplaneTypeLicence, int airplaneTypeSeatsNumber) {
        this.airplaneTypeId = airplaneTypeId;
        this.manufacturer = manufacturer;
        this.airplaneTypeName = airplaneTypeName;
        this.airplaneTypeLicence = airplaneTypeLicence;
        this.airplaneTypeSeatsNumber = airplaneTypeSeatsNumber;
    }
    public Airplanetype(int airplaneTypeId, Manufacturer manufacturer, String airplaneTypeName, String airplaneTypeLicence, int airplaneTypeSeatsNumber, Set<Airplane> airplanes) {
       this.airplaneTypeId = airplaneTypeId;
       this.manufacturer = manufacturer;
       this.airplaneTypeName = airplaneTypeName;
       this.airplaneTypeLicence = airplaneTypeLicence;
       this.airplaneTypeSeatsNumber = airplaneTypeSeatsNumber;
       this.airplanes = airplanes;
    }
   
    public int getAirplaneTypeId() {
        return this.airplaneTypeId;
    }
    
    public void setAirplaneTypeId(int airplaneTypeId) {
        this.airplaneTypeId = airplaneTypeId;
    }
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getAirplaneTypeName() {
        return this.airplaneTypeName;
    }
    
    public void setAirplaneTypeName(String airplaneTypeName) {
        this.airplaneTypeName = airplaneTypeName;
    }
    public String getAirplaneTypeLicence() {
        return this.airplaneTypeLicence;
    }
    
    public void setAirplaneTypeLicence(String airplaneTypeLicence) {
        this.airplaneTypeLicence = airplaneTypeLicence;
    }
    public int getAirplaneTypeSeatsNumber() {
        return this.airplaneTypeSeatsNumber;
    }
    
    public void setAirplaneTypeSeatsNumber(int airplaneTypeSeatsNumber) {
        this.airplaneTypeSeatsNumber = airplaneTypeSeatsNumber;
    }
    public Set<Airplane> getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Set<Airplane> airplanes) {
        this.airplanes = airplanes;
    }




}


