package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private String airportId;
     private String airportName;
     private String airportCity;
     private String airportCountry;
     private int airportPistsNumber;
     private int airportTerminalsNumber;
     private Set<Terminal> terminals = new HashSet<Terminal>(0);
     private Set<Flight> flightsForFlightAirportIdFrom = new HashSet<Flight>(0);
     private Set<Flight> flightsForFlightAirportIdTo = new HashSet<Flight>(0);
     private Set<Gate> gates = new HashSet<Gate>(0);
     private Set<Flight> flightsForFlightExpectedAirportIdTo = new HashSet<Flight>(0);

    public Airport() {
    }

	
    public Airport(String airportId, String airportName, String airportCity, String airportCountry, int airportPistsNumber, int airportTerminalsNumber) {
        this.airportId = airportId;
        this.airportName = airportName;
        this.airportCity = airportCity;
        this.airportCountry = airportCountry;
        this.airportPistsNumber = airportPistsNumber;
        this.airportTerminalsNumber = airportTerminalsNumber;
    }
    public Airport(String airportId, String airportName, String airportCity, String airportCountry, int airportPistsNumber, int airportTerminalsNumber, Set<Terminal> terminals, Set<Flight> flightsForFlightAirportIdFrom, Set<Flight> flightsForFlightAirportIdTo, Set<Gate> gates, Set<Flight> flightsForFlightExpectedAirportIdTo) {
       this.airportId = airportId;
       this.airportName = airportName;
       this.airportCity = airportCity;
       this.airportCountry = airportCountry;
       this.airportPistsNumber = airportPistsNumber;
       this.airportTerminalsNumber = airportTerminalsNumber;
       this.terminals = terminals;
       this.flightsForFlightAirportIdFrom = flightsForFlightAirportIdFrom;
       this.flightsForFlightAirportIdTo = flightsForFlightAirportIdTo;
       this.gates = gates;
       this.flightsForFlightExpectedAirportIdTo = flightsForFlightExpectedAirportIdTo;
    }
   
    public String getAirportId() {
        return this.airportId;
    }
    
    public void setAirportId(String airportId) {
        this.airportId = airportId;
    }
    public String getAirportName() {
        return this.airportName;
    }
    
    public void setAirportName(String airportName) {
        this.airportName = airportName;
    }
    public String getAirportCity() {
        return this.airportCity;
    }
    
    public void setAirportCity(String airportCity) {
        this.airportCity = airportCity;
    }
    public String getAirportCountry() {
        return this.airportCountry;
    }
    
    public void setAirportCountry(String airportCountry) {
        this.airportCountry = airportCountry;
    }
    public int getAirportPistsNumber() {
        return this.airportPistsNumber;
    }
    
    public void setAirportPistsNumber(int airportPistsNumber) {
        this.airportPistsNumber = airportPistsNumber;
    }
    public int getAirportTerminalsNumber() {
        return this.airportTerminalsNumber;
    }
    
    public void setAirportTerminalsNumber(int airportTerminalsNumber) {
        this.airportTerminalsNumber = airportTerminalsNumber;
    }
    public Set<Terminal> getTerminals() {
        return this.terminals;
    }
    
    public void setTerminals(Set<Terminal> terminals) {
        this.terminals = terminals;
    }
    public Set<Flight> getFlightsForFlightAirportIdFrom() {
        return this.flightsForFlightAirportIdFrom;
    }
    
    public void setFlightsForFlightAirportIdFrom(Set<Flight> flightsForFlightAirportIdFrom) {
        this.flightsForFlightAirportIdFrom = flightsForFlightAirportIdFrom;
    }
    public Set<Flight> getFlightsForFlightAirportIdTo() {
        return this.flightsForFlightAirportIdTo;
    }
    
    public void setFlightsForFlightAirportIdTo(Set<Flight> flightsForFlightAirportIdTo) {
        this.flightsForFlightAirportIdTo = flightsForFlightAirportIdTo;
    }
    public Set<Gate> getGates() {
        return this.gates;
    }
    
    public void setGates(Set<Gate> gates) {
        this.gates = gates;
    }
    public Set<Flight> getFlightsForFlightExpectedAirportIdTo() {
        return this.flightsForFlightExpectedAirportIdTo;
    }
    
    public void setFlightsForFlightExpectedAirportIdTo(Set<Flight> flightsForFlightExpectedAirportIdTo) {
        this.flightsForFlightExpectedAirportIdTo = flightsForFlightExpectedAirportIdTo;
    }




}


