package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gate generated by hbm2java
 */
public class Gate  implements java.io.Serializable {


     private int gateId;
     private Airport airport;
     private Terminal terminal;
     private String gateName;
     private Set<Flight> flightsForFlightGateIdTo = new HashSet<Flight>(0);
     private Set<Flight> flightsForFlightGateIdFrom = new HashSet<Flight>(0);

    public Gate() {
    }

	
    public Gate(int gateId, Airport airport, Terminal terminal, String gateName) {
        this.gateId = gateId;
        this.airport = airport;
        this.terminal = terminal;
        this.gateName = gateName;
    }
    public Gate(int gateId, Airport airport, Terminal terminal, String gateName, Set<Flight> flightsForFlightGateIdTo, Set<Flight> flightsForFlightGateIdFrom) {
       this.gateId = gateId;
       this.airport = airport;
       this.terminal = terminal;
       this.gateName = gateName;
       this.flightsForFlightGateIdTo = flightsForFlightGateIdTo;
       this.flightsForFlightGateIdFrom = flightsForFlightGateIdFrom;
    }
   
    public int getGateId() {
        return this.gateId;
    }
    
    public void setGateId(int gateId) {
        this.gateId = gateId;
    }
    public Airport getAirport() {
        return this.airport;
    }
    
    public void setAirport(Airport airport) {
        this.airport = airport;
    }
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }
    public String getGateName() {
        return this.gateName;
    }
    
    public void setGateName(String gateName) {
        this.gateName = gateName;
    }
    public Set<Flight> getFlightsForFlightGateIdTo() {
        return this.flightsForFlightGateIdTo;
    }
    
    public void setFlightsForFlightGateIdTo(Set<Flight> flightsForFlightGateIdTo) {
        this.flightsForFlightGateIdTo = flightsForFlightGateIdTo;
    }
    public Set<Flight> getFlightsForFlightGateIdFrom() {
        return this.flightsForFlightGateIdFrom;
    }
    
    public void setFlightsForFlightGateIdFrom(Set<Flight> flightsForFlightGateIdFrom) {
        this.flightsForFlightGateIdFrom = flightsForFlightGateIdFrom;
    }




}


