package beans;
// Generated Sep 12, 2017 7:50:39 PM by Hibernate Tools 4.3.1



/**
 * Pilotlicence generated by hbm2java
 */
public class Pilotlicence  implements java.io.Serializable {


     private PilotlicenceId id;
     private User user;

    public Pilotlicence() {
    }

    public Pilotlicence(PilotlicenceId id, User user) {
       this.id = id;
       this.user = user;
    }
   
    public PilotlicenceId getId() {
        return this.id;
    }
    
    public void setId(PilotlicenceId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


