package beans;
// Generated Sep 12, 2017 7:50:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Radarcenter generated by hbm2java
 */
public class Radarcenter  implements java.io.Serializable {


     private int radarCenterId;
     private Flight flight;
     private String radarCenterCity;
     private Set<Flightstate> flightstates = new HashSet<Flightstate>(0);

    public Radarcenter() {
    }

	
    public Radarcenter(int radarCenterId) {
        this.radarCenterId = radarCenterId;
    }
    public Radarcenter(int radarCenterId, Flight flight, String radarCenterCity, Set<Flightstate> flightstates) {
       this.radarCenterId = radarCenterId;
       this.flight = flight;
       this.radarCenterCity = radarCenterCity;
       this.flightstates = flightstates;
    }
   
    public int getRadarCenterId() {
        return this.radarCenterId;
    }
    
    public void setRadarCenterId(int radarCenterId) {
        this.radarCenterId = radarCenterId;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public String getRadarCenterCity() {
        return this.radarCenterCity;
    }
    
    public void setRadarCenterCity(String radarCenterCity) {
        this.radarCenterCity = radarCenterCity;
    }
    public Set<Flightstate> getFlightstates() {
        return this.flightstates;
    }
    
    public void setFlightstates(Set<Flightstate> flightstates) {
        this.flightstates = flightstates;
    }




}


