package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rent generated by hbm2java
 */
public class Rent  implements java.io.Serializable {


     private int rentId;
     private Airline airline;
     private Airplane airplane;
     private Integer rentPrice;
     private Date rentDateFrom;
     private Date rentDateTo;
     private Boolean rentIsAccepted;

    public Rent() {
    }

	
    public Rent(int rentId) {
        this.rentId = rentId;
    }
    public Rent(int rentId, Airline airline, Airplane airplane, Integer rentPrice, Date rentDateFrom, Date rentDateTo, Boolean rentIsAccepted) {
       this.rentId = rentId;
       this.airline = airline;
       this.airplane = airplane;
       this.rentPrice = rentPrice;
       this.rentDateFrom = rentDateFrom;
       this.rentDateTo = rentDateTo;
       this.rentIsAccepted = rentIsAccepted;
    }
   
    public int getRentId() {
        return this.rentId;
    }
    
    public void setRentId(int rentId) {
        this.rentId = rentId;
    }
    public Airline getAirline() {
        return this.airline;
    }
    
    public void setAirline(Airline airline) {
        this.airline = airline;
    }
    public Airplane getAirplane() {
        return this.airplane;
    }
    
    public void setAirplane(Airplane airplane) {
        this.airplane = airplane;
    }
    public Integer getRentPrice() {
        return this.rentPrice;
    }
    
    public void setRentPrice(Integer rentPrice) {
        this.rentPrice = rentPrice;
    }
    public Date getRentDateFrom() {
        return this.rentDateFrom;
    }
    
    public void setRentDateFrom(Date rentDateFrom) {
        this.rentDateFrom = rentDateFrom;
    }
    public Date getRentDateTo() {
        return this.rentDateTo;
    }
    
    public void setRentDateTo(Date rentDateTo) {
        this.rentDateTo = rentDateTo;
    }
    public Boolean getRentIsAccepted() {
        return this.rentIsAccepted;
    }
    
    public void setRentIsAccepted(Boolean rentIsAccepted) {
        this.rentIsAccepted = rentIsAccepted;
    }




}


