package beans;
// Generated Sep 14, 2017 1:53:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class Terminal  implements java.io.Serializable {


     private int terminalId;
     private Airport airport;
     private String terminalNaziv;
     private Set<Flight> flightsForFlightTerminalIdTo = new HashSet<Flight>(0);
     private Set<Flight> flightsForFlightTerminalIdFrom = new HashSet<Flight>(0);
     private Set<Gate> gates = new HashSet<Gate>(0);

    public Terminal() {
    }

	
    public Terminal(int terminalId) {
        this.terminalId = terminalId;
    }
    public Terminal(int terminalId, Airport airport, String terminalNaziv, Set<Flight> flightsForFlightTerminalIdTo, Set<Flight> flightsForFlightTerminalIdFrom, Set<Gate> gates) {
       this.terminalId = terminalId;
       this.airport = airport;
       this.terminalNaziv = terminalNaziv;
       this.flightsForFlightTerminalIdTo = flightsForFlightTerminalIdTo;
       this.flightsForFlightTerminalIdFrom = flightsForFlightTerminalIdFrom;
       this.gates = gates;
    }
   
    public int getTerminalId() {
        return this.terminalId;
    }
    
    public void setTerminalId(int terminalId) {
        this.terminalId = terminalId;
    }
    public Airport getAirport() {
        return this.airport;
    }
    
    public void setAirport(Airport airport) {
        this.airport = airport;
    }
    public String getTerminalNaziv() {
        return this.terminalNaziv;
    }
    
    public void setTerminalNaziv(String terminalNaziv) {
        this.terminalNaziv = terminalNaziv;
    }
    public Set<Flight> getFlightsForFlightTerminalIdTo() {
        return this.flightsForFlightTerminalIdTo;
    }
    
    public void setFlightsForFlightTerminalIdTo(Set<Flight> flightsForFlightTerminalIdTo) {
        this.flightsForFlightTerminalIdTo = flightsForFlightTerminalIdTo;
    }
    public Set<Flight> getFlightsForFlightTerminalIdFrom() {
        return this.flightsForFlightTerminalIdFrom;
    }
    
    public void setFlightsForFlightTerminalIdFrom(Set<Flight> flightsForFlightTerminalIdFrom) {
        this.flightsForFlightTerminalIdFrom = flightsForFlightTerminalIdFrom;
    }
    public Set<Gate> getGates() {
        return this.gates;
    }
    
    public void setGates(Set<Gate> gates) {
        this.gates = gates;
    }




}


